[package]
name = "re-delimiter-codec"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "tokio codec with bytes regular expression delimiter using regex crate"
readme = "README.md"
repository = "https://github.com/wobcom/re-delimiter-codec"
keywords = [ "codec", "delimiter", "regex", "tokio" ]
categories = [ "encoding" ]

[dependencies]
regex = "1.13.1"
tokio-util = { version = "0.7.19", features = ["codec"] }

[dev-dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt"] }
tokio-stream = "0.1.19"
tokio-test = "0.4.5"
